name = "rsps"
main = "worker.js"
compatibility_date = "--"
minify =
workers_dev =
no_bundle =
keep_names =

[vars]
REGISTER_TIME_DEDUCT = ""
UNIX_DEDUCT = ""
REGISTER_DEDUCT = ""
FAKE_TICKET = ""
RANDOM_TICKET_ID = ""
ACT_AS_SERVER = ""
D_LOGS = ""
REAL_API_URL = "https://rsps.westeurope.cloudapp.azure.com"

[[d_databases]]
binding = "DB"
database_id = "71f8947a-299e-49e2-8697-7dd4532efb1a"
