name = "rsps"
main = "worker.js"
compatibility_date = "2025-09-28"
minify = false
workers_dev = true
no_bundle = true
keep_names = true

[vars]
REGISTER_TIME_DEDUCT = "0"
UNIX_DEDUCT = "0"
REGISTER_DEDUCT = "0"
FAKE_TICKET = "1"
RANDOM_TICKET_ID = "1"
ACT_AS_SERVER = "1"
D1_LOGS = "0"
REAL_API_URL = "https://rsps.westeurope.cloudapp.azure.com"

[env.dev]
    [[env.dev.d1_databases]]
    binding = "DB"
    database_name = "worker-logs"
    database_id = "71f8947a-299e-49e2-8697-7dd4532efb1a"

[env.prod]
    [[env.prod.d1_databases]]
    binding = "DB"
    database_name = "worker-logs"
    database_id = "71f8947a-299e-49e2-8697-7dd4532efb1a"

[observability]
enabled = true
head_sampling_rate = 1

